# -*- coding: utf-8 -*-
"""10kChallenge_Modelacion.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1oqOwAdZ-K9O_rBokiuJ8mXyDYeEdNJIm
"""

import pandas as pd # importa la librería pandas y la asigna a la variable pd

datos_vida = pd.read_excel('Base_limpia_para_modelo.xlsx') # indicamos el nombre de nuestro archivo a ser leído

datos_vida.head()

datos_vida.groupby("Year").count()

datos_vida.describe()

datos_seleccionados = datos_vida.iloc[:,3:18]

datos_seleccionados # desplegamos el dataframe

datos_seleccionados.info()

datos_seleccionados.isnull().values.any() # buscamos valores nulos y obtenemos True o False dependiendo si hay o no

dataset = datos_seleccionados.dropna() # creamos un nuevo dataframe descartando los valores nulos o vacíos de nuestro dataframe datos_seleccionados

dataset.isnull().sum() # validamos que no tenemos valores nulos en ninguna columna, todos deben dar cero

dataset.columns # vemos los nombres de nuestras columnas para asignarlos a las variables

X = dataset[['Adult.Mortality', 'infant.deaths',
       'percentage.expenditure', 'Measles', 'BMI', 'under.five.deaths',
       'Polio', 'Diphtheria', 'HIV.AIDS', 'thinness..1.19.years',
       'thinness.5.9.years', 'Income.composition.of.resources', 'Schooling',
       'GDP_wb']].values # variables independientes

y = dataset['Life.expectancy'].values # variable dependiente

from sklearn.model_selection import train_test_split # importamos la herramienta para dividir los datos de SciKit-Learn

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0) # asignación de los datos 80% para entrenamiento y 20% para prueba

from sklearn.linear_model import LinearRegression # importamos la clase de regresión lineal

modelo_regresion = LinearRegression() # modelo de regresión

modelo_regresion.fit(X_train, y_train) # aprendizaje automático con base en nuestros datos

x_columns = ['Adult.Mortality', 'infant.deaths',
       'percentage.expenditure', 'Measles', 'BMI', 'under.five.deaths',
       'Polio', 'Diphtheria', 'HIV.AIDS', 'thinness..1.19.years',
       'thinness.5.9.years', 'Income.composition.of.resources', 'Schooling',
       'GDP_wb']
coeff_df = pd.DataFrame(modelo_regresion.coef_, x_columns, columns=['Coeficientes'])
coeff_df

y_pred = modelo_regresion.predict(X_test) # probamos nuestro modelo con los valores de prueba

validacion = pd.DataFrame({'Actual': y_test, 'Predicción': y_pred, 'Diferencia': y_test-y_pred}) # creamos un dataframe con los valores actuales y los de predicción

muestra_validacion = validacion.head(25) # elegimos una muestra con 25 valores 

muestra_validacion # desplegamos esos 25 valores

validacion["Diferencia"].describe()

from sklearn.metrics import r2_score # importamos la métrica R cuadrada (coeficiente de determinación)

r2_score(y_test, y_pred) # ingresamos nuestros valores reales y calculados

import matplotlib.pyplot as plt # importamos la librería que nos permitirá graficar

muestra_validacion.plot.bar(rot=0)  # creamos un gráfico de barras con el dataframe que contiene nuestros datos actuales y de predicción

plt.title("Comparación de esperanza de vida actuales y de predicción") # indicamos el título del gráfico

plt.xlabel("Muestra de países") 

plt.ylabel("Esperanza de vida en años")

plt.show() # desplegamos el gráfico